fanSytem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from loginapp import views
static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('loginapp.urls', namespace='loginapp')),
    path("", include('django.contrib.auth.urls')),

]

loginapp/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

from . import payment
from .tickect import *

app_name = '<loginapp>'

urlpatterns = [

    path('register/', register, name='register'),
    path('', HomeView.as_view(), name='home'),
    path('ticket/<int:pk>/', TicketView.as_view(), name = 'ticket'),
    path('tickets/<int:pk>/', ListTicketView.as_view(), name = 'tickets'),

    path('payment/<int:pk>/', payment.payment, name = 'payment'),
    path('<int:pk>/', payment.repay, name = 'repay'),
    path('successfully/', SuccessfullyView.as_view(), name = 'successfully'),

    # path('', index),
    path('ticket_view/<int:pk><str:tn>/', ViewTicket.as_view(), name="ticket_view"),
    path('ticket_download/<int:pk><str:tn>/', DownloadTicket.as_view(), name="ticket_download"),

    ] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

loginapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)  # a admin user; non super-user
    admin = models.BooleanField(default=False)  # a superuser
    # notice the absence of a "Password field", that is built in.

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []  # Email & Password are required by default.

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active


class Club(models.Model):
    name = models.CharField(max_length=244)
    location = models.CharField(max_length=244)
    def __str__(self):
        return self.name

    
    @property
    def get_total_fans(self):
        if not self.fanprofile.is_staff:
            return self.fanprofile_set.all().count()
    
    @property
    def get_total_staff(self):
        if self.fanprofile.is_staff:
            return self.fanprofile_set.all().count()


FAN_STATUS = (
    ('SAFE', 'SAFE'),
    ('BURNED', 'BURNED'),
)


class FanProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=255)
    club = models.ForeignKey('Club', on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=255, null=True, choices=FAN_STATUS, default=FAN_STATUS[0])

    def __str__(self):
        return str(self.user)


class Match(models.Model):
    home_team = models.CharField(max_length=244, null=True, blank=True)
    away_team = models.CharField(max_length=244, null=True, blank=True)
    date = models.DateTimeField()
    stadium = models.CharField(max_length=244, null=True, blank=True)

    def __str__(self):
        return str(self.home_team) + ' vs ' + str(self.away_team)


class MatchEntrace(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE, null=True, blank=True)
    vip_price = models.PositiveIntegerField()
    mzunguko_price = models.PositiveIntegerField()
    platnum_price = models.PositiveIntegerField()

    def __str__(self):
        return str(self.match) + ' - VIP TSH.' + str(self.vip_price) + '/-, price '  + ' - MZUNGUKO TSH.' + str(self.mzunguko_price)  + '/-, PLATNUM TSH.' + str(self.platnum_price) + '/-'



class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    ticket_number = models.CharField(max_length=255)
    amount = models.PositiveIntegerField(null=True, blank=True)
    match = models.ForeignKey(Match, on_delete=models.CASCADE, null=True, blank=True)
    payed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.ticket_number) + " done by " + str(self.user)


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.PositiveIntegerField()
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, null=True, blank=True)
    due_data  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Tsh." + str(self.amount) + '/- payed by ' + str(self.user)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>home page</title>
<!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">


{% block stylesheet %}

{% endblock stylesheet %}
</head>

<body>
{% block content %}

{% endblock content %}

        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'assets/js/popper.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pgia/lib/pgia.js' %}"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'css/home.css' %}" rel="stylesheet">
{% endblock stylesheet %}
{% block content %}

{% include 'navbar.html' %}
        <div class="container mt-5 text-white">
            <div class="jumbotron shadow-sm mt-5 text-white">
                <h3 class="d-flex justify-content-between align-items-center">
        Trending Match <span class="badge badge-success badge-pill">{{total_match}}</span> </h3>
                <div class="alert alert-success text-center border border-0 border-light" role="alert">
                    Get a ticket for your match today !!
</div>
                <table class="table w-100 text-white"> 
                    <thead> 
                        <tr> 
                            <th>S/N</th> 
                            <th>Match</th> 
                            <th>Stadium</th> 
                            <th>DateTime</th> 
                            <th>Choose</th> 
                        </tr>                         
                    </thead>                     
                    <tbody>
                        {% for match in matchs %} 
                        <tr> 
                            <th scope="row">{{match.id}}</th> 
                            <td>{{match.home_team}} Vs {{match.away_team}}</td> 
                            <td>{{match.stadium}}</td> 
                            <td>{{match.date}}</td> 
                            <td> 
                                {% if request.user.fanprofile.status == 'BURNED' %}
                                    <p class="text-danger">you are not allowed </p>
                                {% else %}
                                    <a class="btn btn-lg btn-info float-right shadow-sm border border-0 border-light" href="{% url 'loginapp:ticket' match.id %}" type="submit" role="button">Get ticket</a>
                                {% endif %}
                                </td>                             
                        </tr> 
                        
                        {% endfor %}
                                              
                    </tbody>                     
                </table>
                
            </div>
        </div>
        {% endblock content %}

templates/malipo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
{{ form.as_p }}
    <button type="submit">Lipa</button>
    </form>
</body>
</html>

templates/myticket.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'css/ticket.css' %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}

        <div class="container">
            
            <div class="jumbotron shadow-sm mt-5">
                <center>
                    <h1 class="text-center display-1" data-pg-ia='{"l":[{"trg":"mouseenter","a":"bounceIn"}]}'>{{home}}  Vs {{away}}</h1>
             
                </center>
                <table class="table"> 
                        <tr> 
                            <td><h2>Customer : {{customer.fanprofile.full_name}}</h2></td> 
                            <td><h2>Stadium : {{stadium}}</h2></td> 
                            <td><h1> Ticket Class : {{status}}</h1></td>                             
                        </tr> 
                    </table>
                    <hr class="my-2">
                    <table class="table">
                        <tr> 
                            <td>Date: {{date}}</td> 
                            <td>Amount: {{amount}}</td> 
                            <td>Status: {{amount}}</td> 
                        </tr>                    
                </table>
                <br><br>
                <center>
                    ****************************************
                    
                    {% if pay_stat %}
                    PAID  -  token <b>{{token}}</b>
                    {% else %}
                    NOT PAID
                    {% endif %}
                        
                    ****************************************
                </center>
            </div>

        </form>
        </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <nav aria-label="breadcrumb">
</nav>

<script>
    function pricechanger() {
        document.getElementById('price').innerHTML= document.getElementById('inlineFormCustomSelect').value;
    }
</script>

{% endblock content %}

templates/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light shadow-lg yellow">
    <div class="container">
        <a class="navbar-brand text-danger font-weight-bold" href="/">FANS TICKETING SYSTEM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <div class=""> 
                <ul>
                {% if request.user.is_authenticated %}
                <a class="btn btn-md btn-outline-danger text-danger" href="{% url 'loginapp:tickets' request.user.pk %}" tabindex="-1" aria-disabled="true">Tickets</a>
                <a class="btn btn-md btn-outline-danger text-danger" href="{% url 'logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
                {% else %}
                <a class="btn btn-md btn-outline-info text-white" href="{% url 'login' %}" tabindex="-1" aria-disabled="true">Login</a>
                {% endif %}
            </ul>
            </div>
        </div>
    </div>
</nav>

templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %}
<link href="{% static 'css/payment.css' %}" rel="stylesheet">
{% endblock stylesheet %}
{% block content %}

{% include 'navbar.html' %}
        <div class="container offset-3">
            <div class="alert alert-success text-center shadow-sm border border-0 border-light" role="alert">
                Payment Successfull ! Ready to save your ticket.
</div>
        </div>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <center> 
            <button type="button" class="btn btn-secondary">Download</button>
        </center>
        
        {% endblock content %}

templates/payments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>paymeny form</title>
</head>
<body>
<h2>love you python</h2>
 <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AYViplmtwkWTbpFbYG_DyDXlz2N7kWv9q_Qk5QiaHoARUmFEc-y_pvsErWmBRF9JmK7-9CvA8r62msYF&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '88.44'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
    </script>
</body>
</html>

templates/ticket.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'css/ticket.css' %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}
{% include 'navbar.html' %}
        <div class="container">
            <form action="{% url 'loginapp:payment' match.pk %}" method="post">
                {% csrf_token %}
            <div class="jumbotron shadow-sm mt-5">
                <h2 class="text-center" data-pg-ia='{"l":[{"trg":"mouseenter","a":"bounceIn"}]}'>
                    <img width="100" style="border-radius: 50%;" src="../../uswazi/media/QQ.jpg" alt="home"> {{match.home_team}} 
                    Vs 
                    <img width="50" style="border-radius: 50%;" src="../static/assets/img/bridge.jpg" alt="away"> {{match.away_team}}</h2>
                <p class="lead text-center p-1">Stadium : {{match.stadium}}</p>
                <table class="table text-white text-center"> 
                    <thead> 
                        <tr> 
                            <th>Date & Day</th> 
                            <th>Amount</th> 
                            <th>Status</th> 
                        </tr>                         
                    </thead>                     
                    <tbody> 
                        <tr> 
                            <th scope="row">{{match.date}}</th> 
                            <!-- price field -->
                            <td name="price" id="price"></td> 
                            <td>
                                <select required name="price" onchange="pricechanger()" class="custom-select border border-light border-0" id="inlineFormCustomSelect" style="background-color: #007789; color: white;">
                                    <option value="" selected="">Choose Status</option>
                                    {% for ent in match.matchentrace_set.all %}
                                    <option value="{{ent.vip_price}}">VIP</option>
                                    <option value="{{ent.platnum_price}}">PLATNUM</option>
                                    <option value="{{ent.mzunguko_price}}">MZUNGUKO</option>
                                    {% endfor %}
                                </select>
                            </td>                             
                        </tr>                         
                    </tbody>                     
                </table>
                <hr class="my-4"/>
                
                {% if messages %}                
                {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <strong>{{message}}</strong>
                </div>

                {% endfor %}
                        
                {% endif %}
                



                {% if request.user.is_authenticated %}

                <div class="dropup" id='cont'>
                    <a role="button" type='button' data-pg-ia='{"l":[{"trg":"click","t":"this","a":"bounce"}]}' class="btn btn-sm btn-warning float-right mr-5 shadow-sm dropdown-toggle" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                                Pay Ticket
                    </a>
                    <ul id="potea" class="dropdown-menu" aria-labelledby="triggerId">
                        <h6 class="dropdown-header">Choose Method</h6>
                        <div class="dropdown-divider"></div>
                        <li onclick="mpesa()" class="dropdown-item">Mpesa</li>
                        <li class="dropdown-item" href="#">Tigopesa</li>
                        <li class="dropdown-item" href="#">Halopesa</li>
                    </ul>
                </div>
                <p>Paid By: <span class="text-white text-capitalize font-weight-bold"> {{request.user.fanprofile.full_name}}</span> </p>
                
                {% else %}
                <p><span class="text-danger text-capitalize font-weight-bold">Guest</span> can't pay for ticket </p>
                <a href="{% url 'login' %}" class="btn btn-lg btn-danger float-right shadow-sm border border-0 border-light" type="submit" role="button" data-pg-ia='{"l":[{"trg":"click","t":"this","a":"bounce"}]}'>Login to pay</a>
                {% endif %}
                    
            </div>

        </form>
        </div>


<script>
    function mpesa(){
        var home = "{{match.home_team}}";
        var away = "{{match.away_team}}";
        var my_price = document.getElementById('price').innerHTML;
        if (my_price){
            var mpesa_number = Number(prompt('Enter Mpesa funded number to make payement\n'))
            if (mpesa_number && typeof mpesa_number == 'number'){
                var mpesa_pin = prompt('You are about to pay ' + my_price + '\n'+
                                    'from '+ mpesa_number +' to FANS TICKETING SYSTEM for \n' 
                                    + home+' vs ' + away + ' match ticket, \n\n'+
                                    'Enter PIN to confirm') 
                if (mpesa_pin == '1234'){
                    done = confirm('confirm payments?');
                    if (done){
                        var container = document.getElementById('cont');
                        var btnn = document.getElementById('triggerId');
                        document.getElementById('potea').hidden = true;
                        btnn.outerHTML = '<button type="submit" data-pg-ia=\'{"l":[{"trg":"click","t":"this","a":"bounce"}]}\' class="btn btn-sm btn-success float-right mr-5 shadow-sm">GO</button>';
                    }

                    } else {
                        alert('Wrong password, try again...')
                    }
                } else {
                    alert('enter valid mpesa number')
                }
            } else {
                alert('choose status first')
            }
        };

    function pricechanger() {
        document.getElementById('price').innerHTML= document.getElementById('inlineFormCustomSelect').value;
    }
</script>

{% endblock content %}

templates/tickets.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'css/home.css' %}" rel="stylesheet">
{% endblock stylesheet %}
{% block content %}

{% include 'navbar.html' %}

<div class="container mt-5 text-white">
    <div class="jumbotron shadow-sm mt-5 text-white">
        <h3 class="d-flex justify-content-between align-items-center">
Tickets<span class="badge badge-success badge-pill">{{total_tickets}}</span> </h3>

<div class="alert alert-success text-center border border-0 border-light" role="alert">
    Hi {{request.user.fanprofile.full_name}}!! {% if matchs %} These are your ticket(s)

</div>

{% if messages %}                
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <strong>{{message}}</strong>
    </div>

    {% endfor %}   
            {% endif %}


        <table class="table w-100 text-white"> 
            <thead> 
                <tr> 
                    <th>S/N</th> 
                    <th>Match</th> 
                    <th>Stadium</th> 
                    <th>Entrace</th> 
                    <th>Date</th> 

                    <th>Status</th> 
                    
                    <th>Token</th> 
                    <th>Action</th> 
                </tr>                         
            </thead>                     
            <tbody>
                {% for match in matchs %} 
                <tr> 
                    <th scope="row">{{forloop.counter}}</th> 
                    <td>{{match.match.home_team}} Vs {{match.match.away_team}}</td> 
                    <td>{{match.match.stadium}}</td> 
                    <td id='price'>{{match.amount}}</td>                           
                    <td>{{match.date}}</td> 

                    {% if match.payed %}
                    <td  class="badge badge-success  mx-1 px-2">
                    Payed
                    {% else %}
                    <td  class="badge badge-danger  mx-1 px-2">
                    Not Payed
                    {% endif %}
                    </td>  

                    <td>{{match.ticket_number}}</td>
                      
                    {% if match.payed %}                    
                    <td><a class="badge badge-primary mx-1 px-2" href="{% url 'loginapp:ticket_view' request.user.pk match.ticket_number %}">view</a><a class="badge badge-success mx-1 px-2" href="{% url 'loginapp:ticket_download' request.user.pk match.ticket_number %}">download</a></td>                           
                    {% else %}
                    <form action="{% url 'loginapp:repay' match.id %}" method="post">
                        {% csrf_token %}
                    <td>
                    
                    
                        <div class="dropup" id='cont'>
                            <a role="button" type='button' data-pg-ia='{"l":[{"trg":"click","t":"this","a":"bounce"}]}' class="btn btn-sm btn-warning float-right mr-5 shadow-sm dropdown-toggle" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                        Pay Ticket
                            </a>
                            <ul id="potea" class="dropdown-menu" aria-labelledby="triggerId">
                                <h6 class="dropdown-header">Choose Method</h6>
                                <div class="dropdown-divider"></div>
                                <li onclick="mpesa()" class="dropdown-item">Mpesa</li>
                                <li class="dropdown-item" href="#">Tigopesa</li>
                                <li class="dropdown-item" href="#">Halopesa</li>
                            </ul>
                        </div>
                    
                    
                    </td>                           
                    </form>     
                    {% endif %}

                </tr> 
                
                {% endfor %}
                                      
            </tbody>                     
        </table>
                        
                  {% else %}
                  have no tickets yet!! <a href="{% url 'loginapp:home' %}">Book here</a>
                {% endif %}
    </div>
    
</div>

<script>
    function mpesa(){
        var home = "{{match.match.home_team}}";
        var away = "{{match.match.away_team}}";
        var my_price = document.getElementById('price').innerHTML;
        if (my_price){
            var mpesa_number = Number(prompt('Enter Mpesa funded number to make payement\n'))
            if (mpesa_number && typeof mpesa_number == 'number'){
                var mpesa_pin = prompt('You are about to pay ' + my_price + '\n'+
                                    'from '+ mpesa_number +' to FANS TICKETING SYSTEM for \n' 
                                    + home+' vs ' + away + ' match ticket, \n\n'+
                                    'Enter PIN to confirm') 
                if (mpesa_pin == '1234'){
                    done = confirm('confirm payments?');
                    if (done){
                        var container = document.getElementById('cont');
                        var btnn = document.getElementById('triggerId');
                        document.getElementById('potea').hidden = true;
                        btnn.outerHTML = '<button type=\'submit\'>GO</button>';
                    }

                    } else {
                        alert('Wrong password, try again...')
                    }
                } else {
                    alert('enter valid mpesa number')
                }
            } else {
                alert('choose status first')
            }
        };

    function pricechanger() {
        document.getElementById('price').innerHTML= document.getElementById('inlineFormCustomSelect').value;
    }
</script>

{% endblock content %}